# Generated by Django 5.1.2 on 2024-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='email',
            field=models.EmailField(default='sacco@mail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
