# Generated by Django 5.1.2 on 2024-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_sacco_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
