# Generated by Django 5.1.2 on 2024-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_sacco_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='has_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sacco',
            name='wallet_creation_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
