# Generated by Django 5.1.2 on 2024-11-15 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0004_sacco_has_wallet_sacco_wallet_creation_failed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_admin', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
