# Generated by Django 5.1.2 on 2024-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0006_alter_sacco_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
